### PR TITLE
fix: call IP() when listenAddr is empty

### LINKED ISSUE #951: panic: Calling IP() on a DomainAddress.
## 你正在使用哪个版本的 V2Ray？

服务端：4.38.3
客户端：4.32.1

## 你的使用场景是什么？

使用手机端v2rayNG绕过大陆及局域网地址代理

## 你看到的异常现象是什么？

v2ray -config /usr/local/etc/v2ray/config.json
V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
A unified platform for anti-censorship.
2021/05/01 03:42:20 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
panic: Calling IP() on a DomainAddress.

goroutine 1 [running]:
github.com/v2fly/v2ray-core/v4/common/net.domainAddress.IP(...)
        github.com/v2fly/v2ray-core/v4/common/net/address.go:164
github.com/v2fly/v2ray-core/v4/app/browserforwarder.(*Forwarder).Start(0xc0006886c0, 0x0, 0x0)
        github.com/v2fly/v2ray-core/v4/app/browserforwarder/forwarder.go:57 +0x127
github.com/v2fly/v2ray-core/v4.(*Instance).Start(0xc0005cdc70, 0x0, 0x0)
        github.com/v2fly/v2ray-core/v4/v2ray.go:337 +0xac
main.main()
        github.com/v2fly/v2ray-core/v4/main/main.go:151 +0x15a

## 你期待看到的正常表现是怎样的？

正常启动

## 请附上你的配置

**服务端配置：**

```javascript
// 在这里附上服务器端配置文件
{
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "debug"
	},
	"dns": {
		"servers": [
			"localhost"
		],
		"clientIp": "1.2.3.4"
	},
	"routing": {
		"domainStrategy": "IPIfNonMatch",
		"domainMatcher": "mph",
		"rules": [{
				"type": "field",
				"ip": [
					"0.0.0.0/8",
					"10.0.0.0/8",
					"100.64.0.0/10",
					"127.0.0.0/8",
					"169.254.0.0/16",
					"172.16.0.0/12",
					"192.0.0.0/24",
					"192.0.2.0/24",
					"192.168.0.0/16",
					"198.18.0.0/15",
					"198.51.100.0/24",
					"203.0.113.0/24",
					"::1/128",
					"fc00::/7",
					"fe80::/10"
				],
				"outboundTag": "blocked"
			},
			{
				"type": "field",
				"outboundTag": "blocked",
				"protocol": [
					"bittorrent"
				]
			},
			{
				"type": "field",
				"domain": ["geosite:category-ads"],
				"outboundTag": "blocked"
			}
		],
		"balancers": []
	},
	"policy": {},
	"inbounds": [{
			"listen": "/var/tmp/v2ray/vmess.sock",
			"protocol": "vmess",
			"settings": {
				"clients": [{
						"id": "（id1已隐去）",
						"alterId": 64
					},
					{
						"id": "（id2已隐去）",
						"alterId": 16
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"acceptProxyProtocol": true,
					"path": "/path_1"
				}
			}
		},
		{
			"listen": "/var/tmp/v2ray/vless.sock",
			"protocol": "vless",
			"settings": {
				"clients": [{
						"id": "（id1已隐去）"
					},
					{
						"id": "（id2已隐去）"
					}
				],
				"decryption": "none"
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"acceptProxyProtocol": true,
					"path": "/path_2"
				}
			}
		}
	],
	"outbounds": [{
			"protocol": "freedom",
			"settings": {}
		},
		{
			"protocol": "blackhole",
			"settings": {},
			"tag": "blocked"
		}
	],
	"transport": {},
	"stats": {},
	"reverse": {},
	"fakedns": [],
	"browserForwarder": {},
	"observatory": {}
}

```

**客户端配置：**

```javascript
// 在这里附上客户端配置
{
	"inbounds": [{
			"port": 10809,
			"listen": "0.0.0.0",
			"protocol": "http",
			"settings": {
				"timeout": 0
			},
			"tag": "proxy-inbound-http"
		},
		{
			"port": 10808,
			"listen": "0.0.0.0",
			"protocol": "socks",
			"settings": {
				"ip": "127.0.0.1",
				"auth": "noauth",
				"udp": true
			},
			"tag": "proxy-inbound-socks"
		}
	],
	"outbounds": [{
			"protocol": "vmess",
			"settings": {
				"vnext": [{
					"address": "地址已隐去",
					"port": 443,
					"users": [{
						"id": "id已隐去",
						"alterId": 16
					}]
				}]
			},
			"streamSettings": {
				"network": "ws",
				"security": "tls",
				"wsSettings": {
					"path": "/path_1",
					"headers": {
						"Host": "example.com"
					}
				}
			},
			"mux": {
				"enabled": true
			},
			"tag": "proxy"
		},
		{
			"protocol": "freedom",
			"settings": {

			},
			"tag": "direct"
		},
		{
			"protocol": "blackhole",
			"settings": {

			},
			"tag": "blocked"
		}
	],
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [{
				"type": "field",
				"outboundTag": "proxy",
				"domain": [
					"services.google.cn"
				]
			},
			{
				"type": "field",
				"ip": [
					"geoip:private"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"geoip:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"protocol": [
					"bittorrent"
				]
			},
			{
				"type": "field",
				"domain": [
					"geosite:category-ads"
				],
				"outboundTag": "blocked"
			}
		]
	}
}
```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

```javascript
// 在这里附上服务器端日志
2021/05/01 03:57:55 [Debug] app/log: Logger started
2021/05/01 03:57:55 [Info] app/dns: DNS: created localhost client
2021/05/01 03:57:55 [Info] app/dns: DNS: client localhost uses clientIP 1.2.3.4
2021/05/01 03:57:55 [Debug] app/router: MphDomainMatcher is enabled for 616 domain rule(s)
2021/05/01 03:57:55 [Debug] app/proxyman/inbound: creating unix domain socket worker on /var/tmp/v2ray/vmess.sock
2021/05/01 03:57:55 [Debug] app/proxyman/inbound: creating unix domain socket worker on /var/tmp/v2ray/vless.sock
2021/05/01 03:57:55 [Info] transport/internet/websocket: listening unix domain socket(for WS) on /var/tmp/v2ray/vmess.sock
2021/05/01 03:57:55 [Warning] transport/internet/websocket: accepting PROXY protocol
2021/05/01 03:57:55 [Info] transport/internet/websocket: listening unix domain socket(for WS) on /var/tmp/v2ray/vless.sock
```

**客户端错误日志：**

```javascript
// 在这里附上客户端日志
（服务端无法启动）
```

## 请附上访问日志

```javascript
// 在这里附上服务器端日志

```

## 其它相关的配置文件（如 Nginx）和相关日志
Nginx - /etc/nginx/nginx.conf
（仅摘录proxy部分）

        location /path_1 {
        	proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
            proxy_pass http://unix:/var/tmp/v2ray/vmess.sock:;
        }
        
        location /path_2 {
        proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
            proxy_pass http://unix:/var/tmp/v2ray/vless.sock:;
        }

## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出

V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
A unified platform for anti-censorship.
2021/05/01 04:02:43 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
Configuration OK.

### PR DESCRIPTION
**Pull request by AkinoKaede**
fix #951

### CODE REVIEW

File: app/browserforwarder/forwarder.go [hunk 1]
```diff
@@ -51,19 +51,21 @@ func (f *Forwarder) Type() interface{} {
...
-	f.forwarder = handler.NewHttpHandle()
-	f.httpserver = &http.Server{Handler: f}
-	address := net.ParseAddress(f.config.ListenAddr)
-	listener, err := internet.ListenSystem(f.ctx, &net.TCPAddr{IP: address.IP(), Port: int(f.config.ListenPort)}, nil)
-	if err != nil {
-		return newError("forwarder cannot listen on the port").Base(err)
-	}
-	go func() {
-		err = f.httpserver.Serve(listener)
+	if f.config.ListenAddr != "" {
```
Comment (Loyalsoldier) [inline app/browserforwarder/forwarder.go:54]: 还需要判断 address 是否为 `localhost`，如果是，就不能直接 `address.IP()`，而要 `address.Domain()`

**Review by Loyalsoldier — APPROVED** [review]
